### ISSUE TITLE
Why specify username?

### ISSUE THREAD

**Issue by dtitov** [Jefferson-Henrique/GetOldTweets#1]
Is it possible to search among all users (all public tweets) without specifying any particular username?

**Comment by Jefferson-Henrique** [comment]
Yes, it is possible. You can ignore (null) the username parameter, like this 

TweetManager.getTweets(**null**, "2015-01-01", "2015-01-02", **"brazil soccer"**)

**Comment by sauravdhr** [comment]
but if i do so i can not get the username of the tweet :[
