### ISSUE TITLE
How is it possible to obtain retweets? From the account (Not from the tweet)

### ISSUE THREAD

**Issue by nyxingen** [Jefferson-Henrique/GetOldTweets#10]
I want to take the old retweets of the accounts, How I can do this?
Thanks for everything !

**Comment by Jefferson-Henrique** [comment]
Sadly I don't know. I have look in Twitter but I only get a few retweets, not all :/

**Comment by Jefferson-Henrique** [comment]
Hi, look what I have found @wurik. It seems that Twitter API only returns the most 100 recent retweets :/

https://dev.twitter.com/rest/reference/get/statuses/retweets/%3Aid
