### ISSUE TITLE
Retweeter or replier username

### ISSUE THREAD

**Issue by winacore** [Jefferson-Henrique/GetOldTweets#11]
Hi,

I would like to know if it's possible to get retweeter username from the example that you propose. Is it possible include mentions and replies (username)?

Maybe you know Nodexl application, which output file shows these informations.

LM

**Comment by Jefferson-Henrique** [comment]
Hello, I think the mentions of a specific tweets are working on the last version, but retweeters are not because I get the same information as Twitter shows on a browser, and there only appears a tiny list of retweeters, not all. However, replies from a tweet seems to be possible, but I didn't develop this feature yet =D.

**Comment by winacore** [comment]
Hi Jefferson. Yes, mentions are working but i didn't see them. I found an information about to build a graph (my problem) with information about tweets and its retweets using getReTweets() method:

http://wenda.soso.io/questions/3148267/twitter4j-build-a-graph-composed-by-tweets-and-their-respectives-retweets

Thanks for your answers.
LM

**Comment by Jefferson-Henrique** [comment]
I have searched here and I have found something interesting, despite it is not good. Look at this link:
https://dev.twitter.com/rest/reference/get/statuses/retweets/%3Aid

You will see that Twitter API only returns the most 100 recent tweets, I think it is the same list that we can fetch through a browser.

**Comment by winacore** [comment]
Oh yes, you are right. The second argument of the method getRetweeterIds(long statusId, long cursor) is maximum 100 disabling pagination. i think you could enhance you application including this feature.

**Comment by Jefferson-Henrique** [comment]
Yeah sure. Thanks for your comments. I wasn't so much happy to implement this before because I think browser has this retweets size limitation, but it is a Twitter API limitation too haha.
