### ISSUE TITLE
Not all tweets seem to download

### ISSUE THREAD

**Issue by wtorsin** [Jefferson-Henrique/GetOldTweets#12]
Hey Jefferson, great application you wrote here.
I used it quite a bit, and I get reasonably good results. However, not all tweets seem to download. I tried this for BarackObama and over the last few days, most tweets get in (retweets don't, which is not the issue) but not all of his tweets of the last few days seem to be included in the app. Is there any reason tweets being excluded?

**Comment by Jefferson-Henrique** [comment]
Yeah, when not logged Twitter's advanced search can response a different list of tweets than you look directly at an user's page.
