### ISSUE TITLE
Geo Location Info

### ISSUE THREAD

**Issue by lumucheng** [Jefferson-Henrique/GetOldTweets#15]
Hi, first off thanks a lot for the great work in creating this project!

Was just wondering if the Geo Location information is being parsed / returned correctly. Currently all the tweets retrieved seems to have it's getGeo() as empty string.

Thanks a lot!

**Comment by Jefferson-Henrique** [comment]
Hello, thanks. I think it was working, but which search parameters are you using? And did you take a look at twitter to see if there you can see geo info?
