### ISSUE TITLE
It does not fetch old tweets. Twitter is distinguishing requests based on user-agent header.

### ISSUE THREAD

**Issue by ramannanda9** [Jefferson-Henrique/GetOldTweets#2]
You need to set the user-agent string to the request header. If you do so it would work.

con.setRequestProperty("User-Agent","Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36");

**Comment by Jefferson-Henrique** [comment]
Hello, you are right the old version of code had some problems because of the lack of request property. But coindentally I have fixed this early this morning hahahh. Thanks anyway =D
