### ISSUE TITLE
Timestamp?

### ISSUE THREAD

**Issue by Jibril2** [Jefferson-Henrique/GetOldTweets#21]
Hello!

I have run your code, but my output file does not include timestamps of a tweet?

EX :
"realDonaldTrump;2016/01/29;3121;9720;"THANK YOU to all of the incredible volunteers.....";ETC

Is there any way to modify this to get something like 2016/01/29 04:37:15?

I see your code has a spot where it declares dates in SDF yyyy-mm-dd HH:mm, but the file itself doesn't see things that way.

**Comment by Jefferson-Henrique** [comment]
Hello, you were using a old version of the jar, I have uploaded the current one where "yyyy-mm-dd HH:mm" works. To include seconds you must change the previous format and build a new jar.

**Comment by SachinIchake** [comment]
Thanks man for the reply.. I am able to fetch old tweets so marked issue as
resolved on GITHUB.
