### ISSUE TITLE
Some tweets are incomplete

### ISSUE THREAD

**Issue by apprenticegirl** [Jefferson-Henrique/GetOldTweets#24]
Hi Jefferson! Thank you so much for this project, I've been searching for something like this from a long time ago.  I'm currently downloading some data and everything seemed to be fine but I checked Output.csv and text is incomplete in some tweets. Am I doing something wrong? This is my query:

`java-jar got.jar querysearch="@manuelacarmena" maxtweets=100`

**Comment by Jefferson-Henrique** [comment]
Hello @apprenticegirl , thanks for your reply. When you mean said the text is incomplete you meant a part of tweet's text or the tweet itself?

**Comment by apprenticegirl** [comment]
Hello Jefferson! I mean, part of the tweet text.  For example:
- Output.csv -> #Feliz15M
- Twitter -> #Feliz15M, por todo lo que nos ha enseñado y todo lo que nos queda por aprender.

**Comment by Jefferson-Henrique** [comment]
Humm, interesting. I will take a look.

**Comment by apprenticegirl** [comment]
Thanks! I will try to do some tests. If I find something particular, I'll let you know :)

**Comment by Jefferson-Henrique** [comment]
Hey @apprenticegirl, can you send me your output.csv?

**Comment by apprenticegirl** [comment]
No problem!
[output_got.zip](https://github.com/Jefferson-Henrique/GetOldTweets-java/files/270871/output_got.zip)

**Comment by Jefferson-Henrique** [comment]
@apprenticegirl in fact the tweet's text seems complete hahah, maybe you were looking for the field specific for hashtags, in this one appears only "Feliz15M". Take a look at the line 12 of your csv file, you will see all the text.

**Comment by apprenticegirl** [comment]
Hahahaha! Sorry! My bad :(  Thank you so much for this.  I'm citing your program on my master's thesis! :)

**Comment by Jefferson-Henrique** [comment]
That's nice, good luck on your research =D.
