### ISSUE TITLE
Support ID export of each tweet

### ISSUE THREAD

**Issue by apas** [Jefferson-Henrique/GetOldTweets#3]
It'd be great to export the ID of each tweet as well.

It's accessible here:  
`<li class="js-stream-item stream-item stream-item expanding-stream-item
" data-item-id="XXXXX" id="stream-item-tweet-XXXXX" data-item-type="tweet">`
and  
`<a href="/username/status/XXXXX" class="tweet-timestamp js-permalink js-nav js-tooltip" data-original-title="11:00 PM - 30 Jun 2015">`

**Comment by Jefferson-Henrique** [comment]
Humm yeah, it will be nice, thanks for contact me. I am going to do this right now.

**Comment by oxygala** [comment]
it'd be awesome if you could separate the mentioned users from the core tweet to a separate tab.

**Comment by apas** [comment]
@Jefferson-Henrique it'd fork, write, and pull request it myself but I was short on time. Read your code, nice job. Looking forward.

**Comment by Jefferson-Henrique** [comment]
Hello @oxygala and @apas, thanks again for your comments, I have just updated the code, now there are four new attributes: mentions, hashtags, id, permalink.

**Comment by apas** [comment]
Thanks @Jefferson-Henrique -- btw, check your mail.
