### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by oxygala** [Jefferson-Henrique/GetOldTweets#5]
Hi, sometimes I get this message and the query is cut off.

java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:504)
    at java.lang.Integer.valueOf(Integer.java:582)
    at me.jhenrique.manager.TweetManager.getTweets(TweetManager.java:96)
    at me.jhenrique.main.Exporter.main(Exporter.java:64)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

What does it refer to? How can we resolve it?

**Comment by Jefferson-Henrique** [comment]
Hello, this error occurs always when you use a specific set of parameters (since, until, username.. etc)? If so can you paste it here?

**Comment by oxygala** [comment]
Hi Jefferson,

I just tried
querysearch="Medeni Yıldırım" and querysearch="Medeni Y&#305;ld&#305;r&#305;m"
and received the aforementioned error in both. 

Thanks.

**Comment by Jefferson-Henrique** [comment]
Hi, sadly I didn't get this error :/. I have executed the last version of "got.jar" and everything goes well. The aforementioned error happens if there is no text information about retweets count.

**Comment by oxygala** [comment]
I will re-clone in a separate directory and retry. Thanks.

**Comment by oxygala** [comment]
I retried in a clean directory and still have the same error. Could it be related to java version? I'm using 1.7.0_80-b15 on a 64-bit Ubuntu 15.10

**Comment by Jefferson-Henrique** [comment]
Can you add this line, right before line 96, on TweetManager? "System.out.println(tweet.toString() + "\n\n");"

We can then debug the response from Twitter when you get the error.

**Comment by oxygala** [comment]
I did. Receiving the exact same error in terminal. Does it log the error somewhere else?

**Comment by Jefferson-Henrique** [comment]
Yeah, as you add this line a new version of "got.jar" needs to be generated if you execute through terminal. Can you give me your email? I can send to you a test version of "got.jar".

**Comment by oxygala** [comment]
As I would expect, the new version did not reproduce the error.

**Comment by oxygala** [comment]
OK, Jefferson I think I had the same error, the query stopped after 20 tweets, here's the debug of last two tweets. 
[javaerror.txt](https://github.com/Jefferson-Henrique/GetOldTweets/files/72163/javaerror.txt)

**Comment by Jefferson-Henrique** [comment]
Sadly both of tweets have this line correct "span class="ProfileTweet-action--retweet u-hiddenVisually" span class="ProfileTweet-actionCount" data-tweet-stat-count="6"". Internally I look for "data-tweet-stat-count", I have tested here with these tweets parsed and get things ok. Sadly I didn't understand why you are facing this problem.

**Comment by Jefferson-Henrique** [comment]
Can you try again on the newest version?

**Comment by oxygala** [comment]
I just did. querysearch="roboski OR uludere since:2011-12-28 until:2011-12-30" instantly spat out the same error.  querysearch="roboski since:2011-12-28 until:2011-12-30" worked.

**Comment by Jefferson-Henrique** [comment]
Humm I have tried here and works fine again. Are you facing the same error? java.lang.NumberFormatException: For input string: ""

**Comment by oxygala** [comment]
yeah. it just happened once though, with that query. I'm trying with other queries, no problem yet.

by the way, my JRE version is 1.7.0_80-b15 on Ubuntu 15.10 64-bit
