### ISSUE TITLE
Is it possible obtain more than 200 favorites tweets from one user with this great tool ?

### ISSUE THREAD

**Issue by nyxingen** [Jefferson-Henrique/GetOldTweets#6]
Is it possible obtain more than 200 favorites tweets from one user with this great tool ?
Thanks for all !

**Comment by Jefferson-Henrique** [comment]
Hello, do you mean the tweets that a specific user click to like?

**Comment by nyxingen** [comment]
Exactly, the list of the tweets that a one specific user click to like

**Comment by Jefferson-Henrique** [comment]
Humm I think it is possible, It is not a public data you must login before get user's like. But thanks for the feature @wurik.

**Comment by nyxingen** [comment]
:) I want to develop this feature, Where you recommend to me to start ?

**Comment by Jefferson-Henrique** [comment]
Nicee =D. Well, as you have to be logged to get user's likes you should start first by logging in twitter. I don't know how is the authentication by browser, I have tried some things it is not the default way, maybe twitter force to do it by oauth. Anyway it is a good question, and any knowledge you get here I will appreciate if you share.
