### ISSUE TITLE
Search tweets based on their Latitude and Longitude

### ISSUE THREAD

**Issue by sehgalvibhor** [Jefferson-Henrique/GetOldTweets#7]
Is there a way to search the tweets based on their LAT and LONG values, just like Tweepy let's you do?

**Comment by Jefferson-Henrique** [comment]
Sadly no, the search made by this library is like twitter search on browser. There is an option there to search near locations, but I never get good results so I didn't put on my code. If you have ideas and other suggestions please reply me.
