### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by nskat** [Jefferson-Henrique/GetOldTweets#9]
Hi,
First I would like to thank you for your work !
However, I have an issue when I try to get a lot of tweets by query search with some keywords. 
I got the following error when I tried to collect 100k tweets containing "Sarkozy" between 2012/23/04 and 2012/05/05  

java.io.IOException: Server returned HTTP response code: 500 for URL: https://twitter.com/i/search/timeline?f=realtime&q=+since%3A2012-04-23+until%3A2012-05-05+Sarkozy&src=typd&max_position=TWEET-198092582553792512-198562641613033472-BD1UO2FFu9QAAAAAAAAETAAAAAcAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at me.jhenrique.manager.TweetManager.getURLResponse(TweetManager.java:61)
    at me.jhenrique.manager.TweetManager.getTweets(TweetManager.java:84)
    at me.jhenrique.main.Main.main(Main.java:50)

The error occured after collecting 22862 tweets. I ran it again and got the same error after collecting 6863 tweets. What's weird is that the program worked just fine when I did the same with "Hollande" as keyword. 
Could you help me fix it ? :)
Thanks a lot !

**Comment by Jefferson-Henrique** [comment]
Hello, this is weird, some people have similiar problems and get things ok when move to another computer. When I try to rerun I never get this errors, Maybe this happens because some java configurations or server-side policies (a lot of requests are made to get tweets). I will try reproduce your seach, who knows if I get the same problem as you and help you better =D.

**Comment by Jefferson-Henrique** [comment]
Can you try again on the newest version?
